controller_server:
  ros__parameters:
    use_sim_time: false
    controller_frequency: 10.0
    controller_plugins: ["FollowPath"]
    goal_checker_plugins: ["goal_checker"]
    goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.15
      yaw_goal_tolerance: 0.2
      stateful: true
    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
      desired_linear_vel: 0.5
      lookahead_dist: 0.6
      use_velocity_scaled_lookahead_dist: false
      use_collision_detection: true
      use_regulated_linear_velocity_scaling: true
      use_cost_regulated_linear_velocity_scaling: true

# 局部代价地图：用激光/深度感知障碍
local_costmap:
  local_costmap:
    ros__parameters:
      use_sim_time: false
      global_frame: cf231/odom            # 你的 Path 也要用这个坐标系（或两者都改成 map）
      robot_base_frame: cf231 # base_link
      rolling_window: true
      width: 5.0
      height: 5.0
      resolution: 0.05
      robot_radius: 0.20            # 或 footprint 多边形，二选一
      update_frequency: 10.0
      publish_frequency: 10.0
      transform_tolerance: 0.3
      plugins: ["obstacle_layer","inflation_layer"]
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: true
        observation_sources: scan
        # scan:
        #   topic: /scan               # 换成你的传感器话题
        #   sensor_frame: laser_frame  # 需有 TF 到 base_link/odom
        #   data_type: LaserScan       # 或 PointCloud2
        #   clearing: true
        #   marking: true
        #   expected_update_rate: 0.0  # 可选；>0 会超时清除
        #   obstacle_range: 3.0
        #   raytrace_range: 3.5
        scan:
          topic: /cf231/scan
          max_obstacle_height: 5.0
          min_obstacle_height: 0.0
          obstacle_max_range: 6.0
          obstacle_min_range: 0.0
          raytrace_max_range: 6.0
          raytrace_min_range: 0.0
          clearing: False
          marking: True
          data_type: "LaserScan"
          inf_is_valid: false
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.55
        cost_scaling_factor: 3.0



# controller_server:
#   ros__parameters:
#     use_sim_time: false
#     controller_frequency: 10.0
#     local_costmap:
#       ros__parameters:
#         global_frame: odom
#         robot_base_frame: cf231/base_link
#         update_frequency: 10.0
#         publish_frequency: 10.0
#         rolling_window: true
#         width: 6.0
#         height: 6.0
#         resolution: 0.05
#         plugins: ['obstacle_layer', 'inflation_layer']
#         obstacle_layer:
#           plugin: "nav2_costmap_2d::ObstacleLayer"
#           observation_sources: scan
#           scan:
#             topic: /scan
#             max_obstacle_height: 2.0
#             clearing: true
#             marking: true
#             data_type: LaserScan
#         inflation_layer:
#           plugin: "nav2_costmap_2d::InflationLayer"
#           cost_scaling_factor: 5.0
#           inflation_radius: 0.5





# # controller：吃你提供的短 Path
# controller_server:
#   ros__parameters:
#     use_sim_time: false
#     controller_frequency: 10.0
#     controller_plugins: ["FollowPath"]
#     FollowPath:
#       plugin: "dwb_core::DWBLocalPlanner"        # 或 regulated_pure_pursuit
#     general_goal_checker:
#       stateful: false
#       xy_goal_tolerance: 0.15
#       yaw_goal_tolerance: 0.2

# # 局部代价地图：用激光/深度感知障碍
# local_costmap:
#   local_costmap:
#     ros__parameters:
#       use_sim_time: false
#       global_frame: odom            # 你的 Path 也要用这个坐标系（或两者都改成 map）
#       robot_base_frame: base_link
#       rolling_window: true
#       width: 5.0
#       height: 5.0
#       resolution: 0.05
#       robot_radius: 0.20            # 或 footprint 多边形，二选一
#       update_frequency: 10.0
#       publish_frequency: 10.0
#       transform_tolerance: 0.3
#       plugins: ["obstacle_layer","inflation_layer"]
#       obstacle_layer:
#         plugin: "nav2_costmap_2d::ObstacleLayer"
#         enabled: true
#         observation_sources: scan
#         scan:
#           topic: /scan               # 换成你的传感器话题
#           sensor_frame: laser_frame  # 需有 TF 到 base_link/odom
#           data_type: LaserScan       # 或 PointCloud2
#           clearing: true
#           marking: true
#           expected_update_rate: 0.0  # 可选；>0 会超时清除
#           obstacle_range: 3.0
#           raytrace_range: 3.5
#       inflation_layer:
#         plugin: "nav2_costmap_2d::InflationLayer"
#         inflation_radius: 0.55
#         cost_scaling_factor: 3.0

# # 生命周期管理
# lifecycle_manager:
#   ros__parameters:
#     autostart: true
#     node_names: ["controller_server","local_costmap"]
