costmap:
  costmap:
    ros__parameters:
      update_frequency: 10.0
      publish_frequency: 10.0
      global_frame: world
      robot_base_frame: cf231
      use_sim_time: False
      rolling_window: True
      width: 6
      height: 6
      resolution: 0.075
      robot_radius: 0.1
      track_unknown_space: true
      plugins: ["obstacle_layer", "inflation_layer"]
      # static_layer:
      #   enabled: False
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        footprint_clearing_enabled: False
        observation_sources: scan
        max_obstacle_height: 5.0
        scan:
          topic: /cf231/scan
          max_obstacle_height: 5.0
          min_obstacle_height: 0.0
          obstacle_max_range: 6.0
          obstacle_min_range: 0.0
          raytrace_max_range: 6.0
          raytrace_min_range: 0.0
          clearing: True
          marking: True
          data_type: "LaserScan"
          inf_is_valid: True
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 10.0
        inflation_radius: 0.1
      always_send_full_costmap: True


# costmap:
#   costmap:
#     ros__parameters:
#       update_frequency: 50.0
#       publish_frequency: 50.0
#       global_frame: cf231/odom
#       robot_base_frame: cf231
#       use_sim_time: True
#       rolling_window: True
#       width: 6
#       height: 6
#       resolution: 0.075
#       robot_radius: 0.23
#       track_unknown_space: false
#       plugins: ["obstacle_layer", "inflation_layer"]
#       obstacle_layer:
#         plugin: "nav2_costmap_2d::ObstacleLayer"
#         enabled: True
#         footprint_clearing_enabled: False
#         observation_sources: scan
#         scan:
#           topic: /cf231/scan
#           max_obstacle_height: 2.0
#           clearing: True
#           marking: True
#           data_type: "LaserScan"
#           raytrace_max_range: 3.0
#           raytrace_min_range: 0.0
#           obstacle_max_range: 2.5
#           obstacle_min_range: 0.0
#         # max_obstacle_height: 5.0
#         # scan:
#         #   topic: /lidar
#         #   max_obstacle_height: 5.0
#         #   min_obstacle_height: 0.0
#         #   obstacle_max_range: 6.0
#         #   obstacle_min_range: 0.0
#         #   raytrace_max_range: 6.0
#         #   raytrace_min_range: 0.0
#         #   clearing: False
#         #   marking: True
#         #   data_type: "LaserScan"
#         #   inf_is_valid: false
#       inflation_layer:
#         plugin: "nav2_costmap_2d::InflationLayer"
#         cost_scaling_factor: Inf
#         inflation_radius: 0.28
#       always_send_full_costmap: True