# named list of all robots
robots:
  cfec:
    enabled: true
    uri: radio://0/80/2M/E7E7E7E7E7
    initial_position: [0.0, 0.0, 0.0]
    type: cf_big  # see robot_types

  cf1:
    enabled: false
    uri: radio://0/80/2M/E7E7E7E701
    initial_position: [0.0, 0.0, 0.0]
    type: cf21  # see robot_types
    # firmware_params:
    #   kalman:
    #     pNAcc_xy: 1.0 # default 0.5
    # firmware_logging:
    #   enabled: true
    #   custom_topics:
    #     topic_name3: 
    #       frequency: 1
    #       vars: ["acc.x", "acc.y"]
  cf5:
    enabled: false
    uri: radio://0/80/2M/E7E7E7E705
    initial_position: [0.0, -0.5, 0.0]
    type: cf21  # see robot_types
    # firmware_params:
    #   kalman:
    #     pNAcc_xy: 1.0 # default 0.5
    #firmware_logging:
    #  custom_topics:
    #    topic_name3: 
    #      frequency: 1
    #      vars: ["acc.x", "acc.y", "acc.z"]

  payload:
    enabled: false
    initial_position: [-0.25, 0.0, 0.0]
    # initial_position: [0.0, 0.0, 0.0]
    type: marker    # see robot_types
    id: 255

# Definition of the various robot types
robot_types:
  cf21:
    motion_capture:
      enabled: true
      # only if enabled; see motion_capture.yaml
      marker: systemid
      dynamics: default
    big_quad: false
    battery:
      voltage_warning: 3.8  # V
      voltage_critical: 3.7 # V
    # firmware_params:
    #   kalman:
    #     pNAcc_xy: 1.0 # default 0.5
    #firmware_logging:
    #   enabled: true
    #   default_topics:
    #   pose:
    #     frequency: 1 # Hz
    #   custom_topics:
    #    topic_name3: 
    #      frequency: 1
    #      vars: ["acc.x", "acc.y", "acc.z"]

  cf21_mocap_deck:
    motion_capture:
      enabled: true
      # only if enabled; see motion_capture.yaml
      marker: mocap_deck
      dynamics: default
    big_quad: false
    battery:
      voltage_warning: 3.8  # V
      voltage_critical: 3.7 # V

    # firmware_params:
    #   kalman:
    #     pNAcc_xy: 1.0 # default 0.5

  # Just a marker to track, not a robot to connect to
  marker:
    connection: none
    motion_capture:
      enabled: true
      marker: default_single_marker
      dynamics: default

  cf_big:
    motion_capture:
      enabled: true
      # only if enabled; see motion_capture.yaml
      marker: default_single_marker
      dynamics: default
    big_quad: true
    battery:
      voltage_warning: 3.8  # V
      voltage_critical: 3.7 # V

# global settings for all robots
all:
  # firmware logging for all drones (use robot_types/type_name to set per type, or
  # robots/drone_name to set per drone)
  firmware_logging:
    enabled: true
    default_topics:
     # remove to disable default topic
      pose:
        frequency: 10 # Hz
      status:
        frequency: 1 # Hz
    #custom_topics:
    #  topic_name1:
    #    frequency: 10 # Hz
    #    vars: ["stateEstimateZ.x", "stateEstimateZ.y", "stateEstimateZ.z", "pm.vbat"]
    #  topic_name2:
    #    frequency: 1 # Hz
    #    vars: ["stabilizer.roll", "stabilizer.pitch", "stabilizer.yaw"]
  # firmware parameters for all drones (use robot_types/type_name to set per type, or
  # robots/drone_name to set per drone)
  firmware_params:
    commander:
      enHighLevel: 1
    # ctrlLee:
    #   Kpos_Px: 12.0 #2.5613 #9.0 # def: 10.0
    #   Kpos_Py: 12.0 #2.4822 #9.0 # def: 10.0
    #   Kpos_Pz: 12.0 #1.0091 # def: 10.0
    #   Kpos_Dx: 8.0 #9.5109 #7.0  # def: 8.0
    #   Kpos_Dy: 8.0 #11.2808 #7.0  # def: 8.0 
    #   Kpos_Dz: 8.0 #1.0125 #  # def: 8.0  
    #   Kpos_Ix: 0.0 # 0.0 #5.0
    #   Kpos_Iy: 0.0 # 0.0 #5.0
    #   Kpos_Iz: 0.0 # 8.0 # 0.0 #8.0
    #   # 0.0265 0.0738 0.0001
    #   KR_x: 0.004 #0.0265 # #0.0055   # def: 0.005  
    #   KR_y: 0.004 #0.0738 # #0.0055  # def: 0.005
    #   KR_z: 0.01 #0.0001 #  #0.008   # def: 0.005
    #   Kw_x: 0.00095 #0.0026  #0.0013 #0.0013 # def: 0.0009
    #   Kw_y: 0.00095 #0.0020  #0.0013 #0.0013  # def: 0.0009
    #   Kw_z: 0.0025  # def: 0.0012
    #   KI_x: 0.003 #0.012 #0.0 #0.012 #0.009 #0.015
    #   KI_y: 0.003 #0.018 #0.0 #0.018 #0.009 #0.015
    #   KI_z: 0.003 #0.015 #0.0 #0.015 #0.009 #0.015
    #   mass: 0.0366

    #   # indi: 3
    #   indi: 0

    #   use_nn: 0

    ctrlLeeP:
      # P load
      # Kpos_Px: 6.0 #18.0
      # Kpos_Py: 6.0 #18.0
      # Kpos_Pz: 6.0 #18.0
      # # D load
      # Kpos_Dx: 8.0 #16.0
      # Kpos_Dy: 8.0 #16.0
      # Kpos_Dz: 8.0 #16.0
      # # I load
      # Kpos_Ix: 0.0 # 5.0
      # Kpos_Iy: 0.0 # 5.0
      # Kpos_Iz: 0.0 # 11.0
      # Kpos_I_limit: 100.0 #0.5

      # # # P attitude Load: 
      # # Kprot_Px: 0.0058
      # # Kprot_Py: 0.0058
      # # Kprot_Pz: 0.0058
      # # #D attitude Load: 
      # # Kprot_Dx: 0.0015
      # # Kprot_Dy: 0.0015
      # # Kprot_Dz: 0.0015
      # # P cable
      # Kqx: 23.0 #19.0
      # Kqy: 23.0 #19.0
      # Kqz: 23.0 #19.0
      # Kq_limit: 0.7
      # # D cable
      # Kwx: 16.0
      # Kwy: 16.0
      # Kwz: 16.0
      # # I cable
      # KqIx: 1.0 #1.0
      # KqIy: 1.0 #1.0
      # KqIz: 1.0 #1.0

      # KR_x: 0.0071 #0.0265 # #0.0055   # def: 0.005  
      # KR_y: 0.0071 #0.0738 # #0.0055  # def: 0.005
      # KR_z: 0.0071 #0.0001 #  #0.008   # def: 0.005
      # Kw_x: 0.0021 #0.0026  #0.0013 #0.0013 # def: 0.0009
      # Kw_y: 0.0021 #0.0020  #0.0013 #0.0013  # def: 0.0009
      # Kw_z: 0.0011  # def: 0.0012
      # KI_x: 0.0 #0.012 #0.0 #0.012 #0.009 #0.015
      # KI_y: 0.0 #0.018 #0.0 #0.018 #0.009 #0.015
      # KI_z: 0.0 #0.015 #0.0 #0.015 #0.009 #0.015
      # mass: 0.0356
      # kpw_xy: 0.0000035

      # # payload properties
      # # massP: 0.017
      # massP: 0.01 # 2 UAV pointmass case
      # # massP: 0.01 # 2 UAV pointmass case
      # # massP: 0.005 # 2 UAV pointmass case
      # # form_ctrl: 3

      Kpos_Px: 17.0
      Kpos_Py: 17.0
      Kpos_Pz: 25.0
      # D load
      Kpos_Dx: 14.0
      Kpos_Dy: 14.0
      Kpos_Dz: 14.0
      # I load
      Kpos_Ix: 5.0
      Kpos_Iy: 5.0
      Kpos_Iz: 10.0
      Kpos_I_limit: 100.0 #0.5

      # P cable
      Kqx: 10.0
      Kqy: 10.0
      Kqz: 10.0
      Kq_limit: 100.0
      # D cable
      Kwx: 9.0
      Kwy: 9.0
      Kwz: 9.0
      # I cable
      KqIx: 1.0
      KqIy: 1.0
      KqIz: 1.0

      # # P angle
      # KRx: 0.0065 #0.0055 #0.008
      # KRy: 0.0065 #0.0055 #0.008
      # KRz: 0.01         #0.01 #0.008
      # # D angle
      # Komx: 0.0012        #0.0013 #0.0017 #0.0013   #0.0017
      # Komy: 0.0012        #0.0013 #0.0017 #0.0013   #0.0017
      # Komz: 0.002          #0.0017
      # # I angle
      # KI_x: 0.03       #0.05 #0.01 #0.009 #0.015
      # KI_y: 0.03        #0.05 #0.01 #0.009 #0.015
      # KI_z: 0.03        #0.05 #0.01 #0.009 #0.015
      # Kpos_Px: 20.0
      # Kpos_Py: 20.0
      # Kpos_Pz: 25.0
      # # D load
      # Kpos_Dx: 16.0
      # Kpos_Dy: 16.0
      # Kpos_Dz: 16.0
      # # I load
      # Kpos_Ix: 5.0
      # Kpos_Iy: 5.0
      # Kpos_Iz: 10.0
      # Kpos_I_limit: 100.0 #0.5
      # # P cable
      # Kqx: 12.0
      # Kqy: 12.0
      # Kqz: 12.0
      # Kq_limit: 100.0
      # # D cable
      # Kwx: 8.0
      # Kwy: 8.0
      # Kwz: 8.0
      # # I cable
      # KqIx: 1.0
      # KqIy: 1.0
      # KqIz: 1.0
      # # mass: 0.034
      # mass: 0.0366
      KRx: 0.005 #0.0265 # #0.0055   # def: 0.005  
      KRy: 0.005 #0.0738 # #0.0055  # def: 0.005
      KRz: 0.01 #0.0001 #  #0.008   # def: 0.005
      Komx: 0.00095 #0.0026  #0.0013 #0.0013 # def: 0.0009
      Komy: 0.00095 #0.0020  #0.0013 #0.0013  # def: 0.0009
      Komz: 0.0025  # def: 0.0012
      KI_x: 0.003 #0.012 #0.0 #0.012 #0.009 #0.015
      KI_y: 0.003 #0.018 #0.0 #0.018 #0.009 #0.015
      KI_z: 0.003 #0.015 #0.0 #0.015 #0.009 #0.015
      mass: 0.0366
      # payload properties
      # massP: 0.017
      # massP: 0.0054 # 2 UAV pointmass case
      massP: 0.0047
      # massP: 0.005 # 2 UAV pointmass case
      # form_ctrl: 3

      ap0id: 3
      ap0x: 0.0
      ap0y: 0.0
      ap0z: 0.0
      ap0l: 0.5 # manual cable length

      ap1id: 9
      ap1x: 0.0
      ap1y: 0.0
      ap1z: 0.0
      ap1l: 0.5 # manual cable length
      form_ctrl: 0
      Kpos_P_limit: 100.0 #0.5 #0.5
      Kpos_D_limit: 100.0 #0.1 #0.1
      radius: 0.1

      gen_hp: 1 # SVM-based hyperplane generation
      en_qdidot: 0 # enable qdidot computation
      setpoint_omega: 0
      # lambda_svm: 10000.0
      lambda_svm: 10.0
      # h_x0: 0.0
      lambda: 20.0

      indi: 0
      est_acc: 2
      use_nn: 0

    quadSysId:
      kappa_f1: 2.0938753372837369e-10
      kappa_f2: 2.2766702598220073e-10
      kappa_f3: 1.906494181367591e-10
      kappa_f4: 2.4578364131636854e-10

    # ring:
    #   effect: 16 # 6: double spinner, 7: solid color, 16: packetRate
    #   solidBlue: 255 # if set to solid color
    #   solidGreen: 0 # if set to solid color
    #   solidRed: 0 # if set to solid color
    #   headlightEnable: 0
    locSrv:
      extPosStdDev: 1e-3
      extQuatStdDev: 0.5e-1
    # kalman:
    #   resetEstimation: 1
    stabilizer:
      estimator: 2 # 1: complementary, 2: kalman
      controller: 5 # 1: PID, 2: mellinger

    ctrlMel:
      mass: 0.114 #0.146 # without camera; 0.160 with camera
      massThrust: 20000 # 132000

    ctrlLee:
      Kpos_Px: 14.0 #2.5613 #9.0 # def: 10.0
      Kpos_Py: 14.0 #2.4822 #9.0 # def: 10.0
      Kpos_Pz: 40.0 #1.0091 # def: 10.0
      Kpos_Dx: 10.0 #9.5109 #7.0  # def: 8.0
      Kpos_Dy: 10.0 #11.2808 #7.0  # def: 8.0 
      Kpos_Dz: 20.0 #1.0125 #  # def: 8.0  
      Kpos_Ix: 0.0 # 0.0 #5.0
      Kpos_Iy: 0.0 # 0.0 #5.0
      Kpos_Iz: 4.0 # 8.0 # 0.0 #8.0
      # 0.0265 0.0738 0.0001
      KR_x: 0.05 #0.0265 # #0.0055   # def: 0.005  
      KR_y: 0.05 #0.0738 # #0.0055  # def: 0.005
      KR_z: 0.06 #0.0001 #  #0.008   # def: 0.005
      Kw_x: 0.006 #0.0026  #0.0013 #0.0013 # def: 0.0009
      Kw_y: 0.006 #0.0020  #0.0013 #0.0013  # def: 0.0009
      Kw_z: 0.006  # def: 0.0012
      KI_x: 0.01 #0.012 #0.0 #0.012 #0.009 #0.015
      KI_y: 0.01 #0.018 #0.0 #0.018 #0.009 #0.015
      KI_z: 0.01 #0.015 #0.0 #0.015 #0.009 #0.015
      mass: 0.130 #0.114 #0.146


    # working
    # ctrlLee:
    #   Kpos_Px: 6.0 #2.5613 #9.0 # def: 10.0
    #   Kpos_Py: 6.0 #2.4822 #9.0 # def: 10.0
    #   Kpos_Pz: 12.0 #1.0091 # def: 10.0
    #   Kpos_Dx: 4.0 #9.5109 #7.0  # def: 8.0
    #   Kpos_Dy: 4.0 #11.2808 #7.0  # def: 8.0 
    #   Kpos_Dz: 8.0 #1.0125 #  # def: 8.0  
    #   Kpos_Ix: 0.0 # 0.0 #5.0
    #   Kpos_Iy: 0.0 # 0.0 #5.0
    #   Kpos_Iz: 0.0 # 8.0 # 0.0 #8.0
    #   # 0.0265 0.0738 0.0001
    #   KR_x: 0.01 #0.0265 # #0.0055   # def: 0.005  
    #   KR_y: 0.01 #0.0738 # #0.0055  # def: 0.005
    #   KR_z: 0.02 #0.0001 #  #0.008   # def: 0.005
    #   Kw_x: 0.0015 #0.0026  #0.0013 #0.0013 # def: 0.0009
    #   Kw_y: 0.0015 #0.0020  #0.0013 #0.0013  # def: 0.0009
    #   Kw_z: 0.0025  # def: 0.0012
    #   KI_x: 0.01 #0.012 #0.0 #0.012 #0.009 #0.015
    #   KI_y: 0.01 #0.018 #0.0 #0.018 #0.009 #0.015
    #   KI_z: 0.01 #0.015 #0.0 #0.015 #0.009 #0.015
    #   mass: 0.130 #0.114 #0.146

    #   # indi: 3
    #   indi: 0

    #   use_nn: 0

    quadSysId:
      thrustToPwmA: 0.1469311028069
      thrustToPwmB: 1.4529883779830977
      thrustToPwmC: -0.1251491261582775

  broadcasts:
    num_repeats: 15 # number of times broadcast commands are repeated
    delay_between_repeats_ms: 1 # delay in milliseconds between individual repeats
