# named list of all robots
robots:
  cf231:
    enabled: True
    # Use URI -OR- id + channel
    # uri: "radio://0/80/2M/E7E7E7E701"
    uri: "radio://0/80/2M/E7E7E7E7E7"
    # id: 1
    # channel: 80
    initial_position: [0,0,0]
    type: "cf21"
    # firmware_params:
    #   kalman:
    #     pNAcc_xy: 1.0 # default 0.5
  cf5:
    enabled: True
    # Use URI -OR- id + channel
    # uri: "radio://0/80/2M/E7E7E7E701"
    uri: "radio://0/80/2M/E7E7E7E705"
    # id: 1
    # channel: 80
    initial_position: [0,-0.5,0]
    type: "cf21"
    # firmware_params:
    #   kalman:
    #     pNAcc_xy: 1.0 # default 0.5

# Definition of the various robot types
robot_types:
  cf21:
    motion_capture:
      enabled: True
      # only if enabled; see motion_capture.yaml
      marker: "default_single_marker"
      dynamics: "default"
    big_quad: False
    battery:
      voltage_warning: 3.8  # V
      voltage_critical: 3.7 # V

  cf21_mocap_deck:
    motion_capture:
      enabled: True
      # only if enabled; see motion_capture.yaml
      marker: "mocap_deck"
      dynamics: "default"
    big_quad: False
    battery:
      voltage_warning: 3.8  # V
      voltage_critical: 3.7 # V

# global settings
settings:
  # firmware parameters for all drones (use types/type_name to set per type, or
  # robots/drone_name to set per drone)
  firmware_params:
    commander:
      enHighLevel: 1
    stabilizer:
      estimator: 2 # 1: complementary, 2: kalman
      controller: 2 # 1: PID, 2: mellinger
    # ring:
    #   effect: 16 # 6: double spinner, 7: solid color, 16: packetRate
    #   solidBlue: 255 # if set to solid color
    #   solidGreen: 0 # if set to solid color
    #   solidRed: 0 # if set to solid color
    #   headlightEnable: 0
    locSrv:
      extPosStdDev: 1e-3
      extQuatStdDev: 0.5e-1
    # kalman:
    #   resetEstimation: 1
