name: System Tests

on:
  push:
    branches: [ "feature_systemtests" ]
  # manual trigger
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Create workspace
        run: |
          pwd
          rm -rf ros2_ws
          mkdir -p ros2_ws/src
      - name: Checkout motion capture package
        run: |
          cd ros2_ws/src
          git clone --branch ros2 --recursive https://github.com/IMRCLab/motion_capture_tracking.git
      - name: Checkout Crazyswarm2
        uses: actions/checkout@v4
        with:
          path: ros2_ws/src/crazyswarm2
          submodules: 'recursive'
      - name: Build workspace
        run: |
          source /opt/ros/humble/setup.bash
          cd ros2_ws
          colcon build --symlink-install

      - name: Flight test
        run: |
          python3 src/crazyswarm2/systemtests/newsub.py

      # - name: build and test ROS 2
      #   uses: ros-tooling/action-ros-ci@v0.3
      #   with:
      #     package-name: |
      #       crazyflie
      #       crazyflie_examples
      #       crazyflie_interfaces
      #       crazyflie_py
      #       crazyflie_sim
      #     target-ros2-distro: humble
      #     vcs-repo-file-url: rosinstall