name: System Tests

on:
  # manual trigger
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: build and test ROS 2
        uses: ros-tooling/action-ros-ci@v0.3
        with:
          package-name: |
            crazyflie
            crazyflie_examples
            crazyflie_interfaces
            crazyflie_py
            crazyflie_sim
          target-ros2-distro: humble
          vcs-repo-file-url: rosinstall